trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- group: docker-secrets

- name: IMAGE
  value: helloworld

- name: REPO
  value: darshilanghan4

- name: TAG
  value: $(Build.BuildNumber)

steps:
- script: |
    chmod +x scripts/builder.sh
    IMAGE=$(IMAGE) \
    REPO=$(REPO) \
    TAG=$(TAG) \
    APP_PATH=app \
    ./scripts/builder.sh
  displayName: Run Builder Script
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: app
    artifactName: app-artifacts
