trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-secrets # contains DOCKER_USERNAME & DOCKER_PASSWORD

  - name: IMAGE
    value: helloworld

  - name: REPO
    value: darshilanghan4

  - name: TAG
    value: $(Build.BuildId)

steps:
  - script: |
      chmod +x scripts/builder.sh

      if [ "$(Build.Reason)" = "PullRequest" ]; then
        echo "Pull Request detected → Build only"
        IMAGE=$(IMAGE) \
        TAG=$(TAG) \
        APP_PATH=. \
        ./scripts/builder.sh
      else
        echo "Push to main → Build and Push"

        # Login to Docker Hub
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        # Build image
        docker build -t $(REPO)/$(IMAGE):$(TAG) .

        # Push image
        docker push $(REPO)/$(IMAGE):$(TAG)
      fi

    displayName: Build & Push Docker Image
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: .
      artifactName: app-artifacts
