trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: docker-secrets # contains DOCKER_USERNAME & DOCKER_PASSWORD

  - name: IMAGE
    value: helloworld

  - name: REPO
    value: darshilanghan4

  - name: TAG
    value: $(Build.BuildId)

steps:
  - script: |
      echo "📁 Moving into APP folder"
      cd APP

      echo "🔧 Making script executable"
      chmod +x scripts/builder.sh

      if [ "$(Build.Reason)" = "PullRequest" ]; then
        echo "🔹 Pull Request → Build only (no push)"
        IMAGE=$(IMAGE) \
        TAG=$(TAG) \
        APP_PATH=. \
        ./scripts/builder.sh

      else
        echo "🚀 Push to main → Build and Push"

        echo "🔐 Logging into Docker Hub"
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        echo "🐳 Building Docker image"
        docker build -t $(REPO)/$(IMAGE):$(TAG) .

        echo "📤 Pushing Docker image"
        docker push $(REPO)/$(IMAGE):$(TAG)

        echo "✅ Image pushed: $(REPO)/$(IMAGE):$(TAG)"
      fi

    displayName: Build & Push Docker Image
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: APP
      artifactName: app-artifacts
